chat_model:
  init_args:
    model: deepseek-chat
    model_provider: openai
    api_key: sk-028228020d844ff58d283cc882d6241b
    base_url: https://api.deepseek.com/v1

image_generator:
  class_path: tools.ImageGeneratorNanobananaGoogleAPI
  init_args:
    api_key: sk-028228020d844ff58d283cc882d6241b
    base_url: http://127.0.0.1:5345

video_generator:
  class_path: tools.VideoGeneratorDoubaoSeedanceOfficialAPI
  init_args:
    api_key: 

working_dir: .working_dir/idea2video
